language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
  - develop
  - /^feature\/.*$/
  - /^hotfix\/.*$/
  - /^release\/.*$/
cache:
  directories:
  - $HOME/.m2
before_script:
  - mvn checkstyle:check cobertura:check pmd:check pmd:cpd-check
script:
  - mvn install
after_success:
  - mvn cobertura:cobertura coveralls:report
