language: java
jdk:
- oraclejdk8
dist: trusty
sudo: required
branches:
  only:
  - master
  - develop
  - /^feature\/.*$/
  - /^hotfix\/.*$/
  - /^release\/.*$/
script:
  - mvn clean install -Ptravis
after_success:
  - mvn coveralls:report -Ptravis
