language: java
jdk:
- oraclejdk8
dist: trusty
sudo: required
env:
  - PROFILE=mysql PROJECT=kangaroo-common
  - PROFILE=mysql PROJECT=kangaroo-server-authz
  - PROFILE=h2 PROJECT=kangaroo-common
  - PROFILE=h2 PROJECT=kangaroo-server-authz
services:
  - mysql
  - docker
branches:
  only:
  - master
  - develop
  - /^feature\/.*$/
  - /^hotfix\/.*$/
  - /^release\/.*$/
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Ptravis
script:
  - mvn install -P$PROFILE -pl $PROJECT
after_success:
  - mvn coveralls:report -Ptravis
