language: java
jdk:
- oraclejdk8
dist: trusty
sudo: required
env:
  - PROFILE=mysql
  - PROFILE=h2
services:
  - mysql
branches:
  only:
  - master
  - develop
  - /^feature\/.*$/
  - /^hotfix\/.*$/
  - /^release\/.*$/
script:
  - mvn clean install -Ptravis -P$PROFILE
after_success:
  - mvn coveralls:report -Ptravis
