language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
  - develop
  - /^feature\/.*$/
  - /^hotfix\/.*$/
  - /^release\/.*$/
before_script:
  - mvn clean -Ptravis
  - mvn checkstyle:check -Ptravis
  - mvn cobertura:check -Ptravis
  - mvn pmd:check -Ptravis
  - mvn pmd:cpd-check -Ptravis
script:
  - mvn install -Ptravis
after_success:
  - mvn cobertura:cobertura coveralls:report -Ptravis
